@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2MwNzJkZGM1YzU3ZjgxZDYwYWZlMjYiLCJpYXQiOjE3NDA4NDU3ODYsImV4cCI6MTc0MDkzMjE4Nn0.9J-OIDIbYtoAc1ApS2W8wrayNEeO8dAYzcGtfjFSbDk
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2MwNzJkZGM1YzU3ZjgxZDYwYWZlMjYiLCJpYXQiOjE3NDA4NDQ2MjZ9.9BZlm0Q3kwMi9zNdCq3Ceiy9GwydYBisWXsIJ59xcWg
@posterId = 67c072ddc5c57f81d60afe26
@postId = 67c345030517efec8c22b4bf
@commentId = 6748901949152b8687e00985
@userId = 67c072ddc5c57f81d60afe26

### posts API

POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "posterId": "{{posterId}}",
    "description": "test for likes"
}
###

GET http://localhost:3000/posts
Authorization: Bearer {{token}}

###

GET http://localhost:3000/posts/{{postId}}
Authorization: Bearer {{token}}

###

GET http://localhost:3000/posts/poster?id={{posterId}}
Authorization: Bearer {{token}}

###

PUT http://localhost:3000/posts/{{postId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "message": "message to updateA"
}

### messages API

POST http://localhost:3000/comments
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "posterId": "{{posterId}}",
    "content": "This is a comment for test",
    "postId": "{{postId}}"
}

###

GET http://localhost:3000/comments
Authorization: Bearer {{token}}

###

GET http://localhost:3000/comments/{{commentId}}
Authorization: Bearer {{token}}

###

GET http://localhost:3000/comments/post/{{postId}}
Authorization: Bearer {{token}}

###

PUT http://localhost:3000/comments/{{commentId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "Updated comment content"
}

###

DELETE http://localhost:3000/comments/{{commentId}}
Authorization: Bearer {{token}}

### Users API

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "0123meir",
    "email": "0123meir@gmail.com",
    "password": "1234"
}
###

GET http://localhost:3000/users
Authorization: Bearer {{token}}

###

GET http://localhost:3000/users/{{userId}}
Authorization: Bearer {{token}}

###
PUT http://localhost:3000/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "meirA",
    "email" : "user@myDaifferentAwsomeDomain.coma"
}

###
DELETE http://localhost:3000/users/{{userId}}
Authorization: Bearer {{token}}

### auth API

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "newuser",
    "email": "newuser@example.com",
    "password": "securepassword"
}
###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "0123meir@gmail.com",
    "password": "1234"
}
###

POST http://localhost:3000/auth/logout
Authorization: Bearer {{refreshToken}}

###

POST http://localhost:3000/auth/refreshToken
Authorization: Bearer {{refreshToken}}

###

POST http://localhost:3000/likes/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "postId": "{{postId}}"
}

###

DElETE http://localhost:3000/likes/{{postId}}
Content-Type: application/json
Authorization: Bearer {{token}}