@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M5YjE3YzdmYzI2NjQ2N2RhOTdhMDgiLCJpYXQiOjE3NDE0NTA5NTAsImV4cCI6MTc0MTUzNzM1MH0.-N1MHj-Hlf5Db91padXaxx7WEASY8mViRv12A6TDHso
@refreshToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M5YjE3YzdmYzI2NjQ2N2RhOTdhMDgiLCJpYXQiOjE3NDE0NTA5NTB9.JO77pR-ae_pzFtV-eePuG9hSMOxxonRlG7kHtioA-GY
@posterId = 67ca46d7dd3a0654713c7c08
@postId = 67cc7577d81184ac827816eb
@commentId = 6748901949152b8687e00985
@userId = 67ca46d7dd3a0654713c7c08

### posts API

POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "posterId": "{{posterId}}",
    "description": "test for profile image"
}
###

GET http://localhost:3000/posts
Authorization: Bearer {{token}}

###

GET http://localhost:3000/posts/{{postId}}
Authorization: Bearer {{token}}

###

GET http://localhost:3000/posts/poster?id={{posterId}}
Authorization: Bearer {{token}}

###

PUT http://localhost:3000/posts/{{postId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "message": "message to updateA"
}

### messages API

POST http://localhost:3000/comments
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "posterId": "{{posterId}}",
    "content": "This is a comment for test",
    "postId": "{{postId}}"
}

###

GET http://localhost:3000/comments
Authorization: Bearer {{token}}

###

GET http://localhost:3000/comments/{{commentId}}
Authorization: Bearer {{token}}

###

GET http://localhost:3000/comments/post/{{postId}}
Authorization: Bearer {{token}}

###

PUT http://localhost:3000/comments/{{commentId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "Updated comment content"
}

###

DELETE http://localhost:3000/comments/{{commentId}}
Authorization: Bearer {{token}}

### Users API

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "0123meir",
    "email": "0123meir@gmail.com",
    "password": "1234"
}
###

GET http://localhost:3000/users
Authorization: Bearer {{token}}

###

GET http://localhost:3000/users/{{userId}}
Authorization: Bearer {{token}}

###
PUT http://localhost:3000/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "meirA",
    "email" : "user@myDaifferentAwsomeDomain.coma"
}

###
DELETE http://localhost:3000/users/{{userId}}
Authorization: Bearer {{token}}

### auth API

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "testImageUser",
    "email": "testUser@example.com",
    "password": "1234"
}
###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "0123meir111@gmail.com",
    "password": "1234"
}
###

POST http://localhost:3000/auth/logout
Authorization: Bearer {{refreshToken}}

###

POST http://localhost:3000/auth/refreshToken
Authorization: Bearer {{refreshToken}}

###

POST http://localhost:3000/likes/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "postId": "{{postId}}"
}

###

DElETE http://localhost:3000/likes/{{postId}}
Content-Type: application/json
Authorization: Bearer {{token}}